version: '3.9'

networks:
    laravel-backend-network:
        driver: bridge

services:
  web:
    build: .
    image: laravel_backend_web_server_image
    container_name: laravel_backend_web_server_container
    hostname: web_server
    ports:
      - 9001:80
    #volumes:
    #  - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db_server
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: password
    networks:
        - laravel-backend-network

  db:
    image: mysql:8.0
    container_name: laravel_backend_db_server_container
    hostname: db_server
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata1:/var/lib/mysql
    networks:
        - laravel-backend-network

volumes:
  dbdata1:
